#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: strapi
  newName: strapi/strapi
  newTag: 3.0.6-alpine

vars:
- fieldref:
    fieldPath: metadata.name
  name: STRAPI_SERVICE_NAME
  objref:
    apiVersion: v1
    kind: Service
    name: strapi

secretGenerator:
- envs:
  - secret.env
  name: strapi-env-secret

configMapGenerator:
- envs:
  - config.env
  name: strapi-env
- files:
  - strapi_configure.sh
  name: strapi-config

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- deployment.yml
- service.yml
