# 
# Copyright SecureKey Technologies Inc. All Rights Reserved. 
# 
# SPDX-License-Identifier: Apache-2.0 
# 

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: postgres-demo
spec:
  ports:
  - name: postgres-port
    port: 5432
    protocol: TCP
    targetPort: postgres-port
  selector:
    app: postgres-demo
status:
  loadBalancer: {}
