#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-issuer
  labels:
    app: issuer
spec:
  tls:
  - hosts:
      - demo-issuer.||DOMAIN||
    secretName: INGRESS_TLS_SECRET
  rules:
  - host: demo-issuer.||DOMAIN||
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: ISSUER_SERVICE_NAME
            port:
              name: http
