#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: mysql-demo
spec:
  ports:
  - name: mysql-port
    port: 3306
    protocol: TCP
    targetPort: mysql-port
  selector:
    app: mysql-demo
status:
  loadBalancer: {}
