#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
kind: Job
apiVersion: batch/v1
metadata:
  name: auth-hydra-create-client
  labels:
    group: core
    component: auth
spec:
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: healthcheck-ready
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"]
          args:
            - "-c"
            - |
              while [[ "$(wget -T 5 -S --spider http://auth-hydra-admin/health/ready 2>&1 | grep '200 OK')" == "" ]];
              do echo "waiting for endpoint";
              sleep 5;
              done;
      containers:
      - name: hydra-clients-create
        image: "oryd/hydra:v1.3.2-alpine"
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args:
          - "-c"
          - |
            err_resp=$(hydra clients create --endpoint http://auth-hydra-admin --fake-tls-termination --id test-org --secret test-org-secret --grant-types client_credentials --response-types token,code --scope org_admin --skip-tls-verify 2>&1 > /dev/null);
            echo $err_resp;
            if [ -z "$err_resp" ] || [ -n "$(echo ${err_resp} | grep already )" ];then echo "hydra client add successful"; exit 0;else echo "hydra client add failed"; exit 1;fi
