# 
# Copyright SecureKey Technologies Inc. All Rights Reserved. 
# 
# SPDX-License-Identifier: Apache-2.0 
# 

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: hydra
  newName: oryd/hydra
  newTag: v1.3.2-alpine

vars:
- fieldref:
    fieldPath: metadata.name
  name: HYDRA_PUBLIC_SERVICE_NAME
  objref:
    apiVersion: v1
    kind: Service
    name: hydra
- fieldref:
    fieldPath: metadata.name
  name: HYDRA_ADMIN_SERVICE_NAME
  objref:
    apiVersion: v1
    kind: Service
    name: hydra-admin

secretGenerator:
- envs:
  - hydra-secret.env
  name: hydra-secret

configMapGenerator:
- envs:
  - hydra-env.env
  name: hydra-env

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- hydra.yml
