# 
# Copyright SecureKey Technologies Inc. All Rights Reserved. 
# 
# SPDX-License-Identifier: Apache-2.0 
# 

apiVersion: svceng
kind: SedB64Transformer
metadata:
  name: sedb64transformer
argsOneLiner: s^||MONGODB_URL||^${MONGODB_URL}^ s^||EXTERNAL_API_CLIENTID||^${EXTERNAL_API_CLIENTID}^ s^||EXTERNAL_API_CLIENTSECRET||^${EXTERNAL_API_CLIENTSECRET}^ s^||OAUTH2_EXTERNAL_CLIENT_ID||^${OAUTH2_EXTERNAL_CLIENT_ID}^ s^||OAUTH2_EXTERNAL_CLIENT_SECRET||^${OAUTH2_EXTERNAL_CLIENT_SECRET}^