# 
# Copyright SecureKey Technologies Inc. All Rights Reserved. 
# 
# SPDX-License-Identifier: Apache-2.0 
# 

- hosts: localhost
  gather_facts: no

  vars_files:
    - healthchecks.yml

  tasks:
    - name: checking 
      uri:
        url: "{{ item.uri }}"
        validate_certs: false
        timeout: 10
        status_code: "{{ item.code }}"
      register: _result
      until: _result.status == item.code
      retries: 3
      delay: 5
      loop: "{{ healthcheck }}"
      loop_control:
        label: "{{ item.name }}"


