# 
# Copyright SecureKey Technologies Inc. All Rights Reserved. 
# 
# SPDX-License-Identifier: Apache-2.0 
# 

# Adds namespace to all resources.
#namespace: edge-sandbox-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
commonLabels:
  component: cms
  group: demo
  instance: local
  project: trustbloc


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- strapi/ingress.yml
- strapi/user-data.yml
- oathkeeper/ingress.yml
- oathkeeper/role.yml
- oathkeeper/rolebinding.yml
- oathkeeper/process-template.yml


transformers:
- sedtransform.yml
- sedb64transform.yml

components:
- ../../components/strapi
- ../../components/oathkeeper

vars:
- fieldref:
    fieldPath: metadata.name
  name: INGRESS_TLS_SECRET
  objref:
    apiVersion: v1
    kind: Secret
    name: cms-wildcard-cert


secretGenerator:
- files:
  - certs/tls.crt
  - certs/tls.key
  name: cms-wildcard-cert
  type: kubernetes.io/tls

configMapGenerator:
- files:
  - strapi/user_data.sh
  name: strapi-user-data-script
- behavior: replace
  files:
  - oathkeeper/config.yml
  name: oathkeeper-config
- files:
  - oathkeeper/process_template.sh
  name: process-template-script
- files:
  - oathkeeper/access-rules.tmpl
  name: access-rules-template
- files:
  - certs/ca.crt
  name: oathkeeper-ca-cert

patchesStrategicMerge:
- oathkeeper/update-local-cert-store.yml
