# 
# Copyright SecureKey Technologies Inc. All Rights Reserved. 
# 
# SPDX-License-Identifier: Apache-2.0 
# 

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: issuer
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - update
  - patch
  - watch
- apiGroups:
  - "apps"
  resources:
  - deployments
  resourceNames:
  - "issuer"
  verbs:
  - get
  - patch
