# 
# Copyright SecureKey Technologies Inc. All Rights Reserved. 
# 
# SPDX-License-Identifier: Apache-2.0 
# 

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: rp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rp
  template:
    metadata:
      labels:
        app: rp
    spec:
      imagePullSecrets:
      - name: rp-github-regcred
      containers:
      - name: rp
        envFrom:
          - configMapRef:
              name: rp-env
          - secretRef:
              name: rp-env-secret
        image: sandbox-rp:latest
        args: ["start"]
        ports:
          - containerPort: 8081
            protocol: TCP
            name: http-port
