# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0


name: $(SourceBranchName)-$(Date:yyyyMMdd).$(Rev:r)
trigger:
  - master
pr:
  - master

variables:
  GO_VERSION: 1.13
  GOPATH: $(Agent.BuildDirectory)/go

jobs:
  - job: Checks
    pool:
      vmImage: ubuntu-18.04
    timeoutInMinutes: 30
    steps:
      - template: azp-dependencies.yml
      - checkout: self
      - script: make checks
        displayName: Run checks

  - job: UnitTest
    pool:
      vmImage: ubuntu-18.04
    timeoutInMinutes: 30
    steps:
      - template: azp-dependencies.yml
      - checkout: self
      - script: make unit-test
        displayName: Run unit test
      - script: bash <(curl https://codecov.io/bash) -t $CODECOV_UPLOAD_TOKEN
        env:
          CODECOV_UPLOAD_TOKEN: $(CODECOV_UPLOAD_TOKEN)
        displayName: Upload coverage to Codecov

  - job: Publish
    dependsOn:
      - Checks
      - UnitTest
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    pool:
      vmImage: ubuntu-18.04
    timeoutInMinutes: 30
    steps:
      - template: azp-dependencies.yml
      - checkout: self
      - bash: |
          function logout {
            docker logout
          }
          trap logout EXIT
          git lfs install
          git lfs pull
          source ci/version_var.sh
          echo $DOCKER_PASSWORD | docker login docker.pkg.github.com --username $DOCKER_USER --password-stdin
          make issuer-rest-docker rp-rest-docker login-consent-server-docker
          docker tag docker.pkg.github.com/trustbloc/edge-sandbox/issuer-rest:latest ${ISSUER_REST_PKG}:${EDGE_SANDBOX_TAG}
          docker push ${ISSUER_REST_PKG}:${EDGE_SANDBOX_TAG}
          docker tag docker.pkg.github.com/trustbloc/edge-sandbox/rp-rest:latest ${RP_REST_PKG}:${EDGE_SANDBOX_TAG}
          docker push ${RP_REST_PKG}:${EDGE_SANDBOX_TAG}
          docker tag docker.pkg.github.com/trustbloc/edge-sandbox/login-consent-server:latest ${LOGIN_REST_PKG}:${EDGE_SANDBOX_TAG}
          docker push ${LOGIN_REST_PKG}:${EDGE_SANDBOX_TAG}
        env:
          DOCKER_USER: $(DOCKER_USER)
          DOCKER_PASSWORD: $(DOCKER_PASSWORD)
