#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  component: benefits-dept-rp

vars:
- fieldref:
    fieldPath: metadata.name
  name: BENEFITS_DEPT_RP_SERVICE_NAME
  objref:
    apiVersion: v1
    kind: Service
    name: rp

configMapGenerator:
- envs:
  - config.env
  behavior: merge
  name: ace-rp-env

namePrefix: benefits-dept-

resources:
- ../../base
