# 
# Copyright SecureKey Technologies Inc. All Rights Reserved. 
# 
# SPDX-License-Identifier: Apache-2.0 
# 

# Adds namespace to all resources.
#namespace: edge-sandbox-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
commonLabels:
  component: login-consent
  group: demo
  instance: local
  project: trustbloc


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

vars:
- fieldref:
    fieldPath: metadata.name
  name: INGRESS_TLS_SECRET
  objref:
    apiVersion: v1
    kind: Secret
    name: login-consent-wildcard-cert

secretGenerator:
- behavior: merge
  envs:
  - hydra/hydra-secret.env
  name: hydra-secret
- files:
  - certs/tls.crt
  - certs/tls.key
  name: login-consent-wildcard-cert
  type: kubernetes.io/tls

configMapGenerator:
- behavior: merge
  envs:
  - hydra/hydra-env.env
  name: hydra-env
- files:
  - certs/ca.crt
  name: login-consent-ca-cert
- behavior: merge
  envs:
  - login-consent/login-consent.env
  name: login-consent-env


resources:
- ../../base
- login-consent/ingress.yml
- hydra/hydra-create-client.yml

transformers:
- sedtransform.yml
- sedb64transform.yml

components:
- ../../components/hydra

patchesStrategicMerge:
- login-consent/add-ca.yml
