# 
# Copyright SecureKey Technologies Inc. All Rights Reserved. 
# 
# SPDX-License-Identifier: Apache-2.0 
# 

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: mongodb-demo
spec:
  ports:
  - name: mongodb-port
    port: 27017
    protocol: TCP
    targetPort: mongodb-port
  selector:
    app: mongodb-demo
status:
  loadBalancer: {}
